# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=32505856
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: data540
      MYSQL_USER: data540
      MYSQL_PASSWORD: data540
      MYSQL_DATABASE: data540
    volumes:
      - ./db-data:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
